[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
anchor_marketplace = "FqJ7dcjXWeo5hUfEWXcJLzrYoyUBy93CxWfeXZDYkjXZ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
# wallet = "~/.config/solana/id.json"
wallet = "./turbin3-wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
